on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    container: ghcr.io/lwakefield/gh-org-stats:main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
          GH_ORGS: ${{ secrets.GH_ORGS }}
        continue-on-error: true
        run: /bin/gh-org-stats update $GH_ORGS
      - run: |
          rm -rf ./report
          /bin/gh-org-stats report ./report

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./report
          git commit -m "Update report"
          git push
